[versions]
# kotlin
kotlin = "2.2.0"
kotlin-dsl = "6.5.2"
serialization = "1.9.0"

[libraries]
# build
build-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
build-kotlin-dsl = { module = "org.gradle.kotlin:gradle-kotlin-dsl-plugins", version.ref = "kotlin-dsl" }
build-kotlin-multiplatform = { module = "org.jetbrains.kotlin.multiplatform:org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "kotlin" }

[bundles]
build = [
    "build-kotlin-multiplatform",
    "build-kotlin-dsl",
    "build-serialization",
]
